### ISSUE TITLE
failed to install on Debian

### ISSUE THREAD

**Issue by connected201** [andrey42/zfs-hetzner-vm#7]
hi, after ~2 minute installation, i have this error:
![image](https://user-images.githubusercontent.com/20506433/83923479-0e464380-a78b-11ea-851c-4bc3efea23d5.png)
i loaded from linux_x64. all ok,

**Comment by andrey42** [comment]
if wipefs cannot cleanup your disk, then check whether your disk is really unmounted and there are no processes using it
you can use lsof utility for it
````
lsof | grep '/dev/put_device_id_here'
````

**Comment by connected201** [comment]
empty
![image](https://user-images.githubusercontent.com/20506433/83980076-7035b300-a91b-11ea-829a-a552acc7a8c0.png)

**Comment by connected201** [comment]
i can give to you ssh access in rescue mode this server is empty, so, you can delete all data.
also, i speak Russian very well...

**Comment by connected201** [comment]
i deteled all data from my ssd, it's not help!

**Comment by andrey42** [comment]
Cannot reproduce the issue you claimed.
I've created hetzner VM machine with 2Gb memory and 20Gb disk, used script, paritioning works correctly. Extract from the log output /tmp/zfs-hetzner-vm/install.log :
````
+ zfs --version
+ echo '======= partitioning the disk =========='
+ [[ 0 -eq 0 ]]
+ tail_space_parameter=0
+ for selected_disk in "${v_selected_disks[@]}"
+ wipefs --all /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0
+ sgdisk -a1 -n1:24K:+1000K -t1:EF02 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0
+ sgdisk -n2:0:+512M -t2:BF01 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0
+ sgdisk -n3:0:0 -t3:BF01 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0
+ udevadm settle

````

**Comment by connected201** [comment]
give me your email or telegram, i will give SSH access to my server,thanks, best regards

**Comment by andrey42** [comment]
you have to contact hetzner support for reasons why your disk cannot be wiped

**Comment by connected201** [comment]
wipefs --all /dev/sda
/dev/sda: 8 bytes were erased at offset 0x37e483f000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e483e000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e483d000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e483c000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e483b000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e483a000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4839000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4838000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4837000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4836000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4835000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4834000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4833000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4832000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4831000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4830000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482f000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482e000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482d000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482c000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482b000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e482a000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4829000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4828000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4827000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4826000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4825000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4824000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4823000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487f000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487e000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487d000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487c000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487b000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e487a000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4879000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4878000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4877000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4876000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4875000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4874000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4873000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4872000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4871000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4870000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486f000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486e000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486d000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486c000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486b000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e486a000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4869000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4868000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4867000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4866000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4865000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4864000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4863000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4862000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4861000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x37e4860000 (zfs_member): 0c b1 ba 00 00 00 00 00
/dev/sda: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: 8 bytes were erased at offset 0x37e4895e00 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
/dev/sda: calling ioctl to re-read partition table: Success

same with /dev/sdb, i execute wipefs --all /dev/sda nad wipefs --all /dev/sdb, all ok!
